
project_id = "tmsgxatsxpvhsuydttzp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = 52428800

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[functions]

[functions.update-user-role]
verify_jwt = true

[functions.update-user-manager]
verify_jwt = true

