// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmsgxatsxpvhsuydttzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtc2d4YXRzeHB2aHN1eWR0dHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjE4MzAsImV4cCI6MjA2MTczNzgzMH0.Njy2OuLVVnZ6o5AnFuyp573s_AyAvF60thLTH_KGNOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);